@userName = OpenShift
//@userName = Kreebog
@adminKey = a3JlZWJvZzoxc3VwZXIx 
@assistantKey = RFJvZ2VyczpEUm9nZXJz
@invalidKey = dGVzdDpndXk=
@ocpKey = b3BlbnNoaWZ0Ok9wZW5TaGlmdF9QYXNzd29yZA==

### Request probes with invalid USER
GET http://localhost:8083/api/team/probes/live HTTP/1.1
Authorization: Basic {{ocpKey}}

### Rquest list of users
GET http://localhost:8083/api/team/get/user HTTP/1.1
Authorization: Basic {{ocpKey}}

### Request count of teams
GET http://localhost:8083/api/team/count HTTP/1.1
Authorization: Basic {{assistantKey}}

### Request list of teams
GET http://localhost:8083/api/team/get HTTP/1.1
Authorization: Basic {{adminKey}}

### Request specific user
GET http://localhost:8083/api/team/get/user?userName=OpenShift HTTP/1.1
Authorization: Basic {{adminKey}}

### Update User
PUT http://localhost:8083/api/team/update/user HTTP/1.1
Authorization: Basic {{adminKey}}
Content-Type: application/json

 {
    "id": "OpenShift",
    "userName": "openshift",
    "firstName": "Open",
    "lastName": "Shift",
    "teamId": "N/A",
    "botId": "N/A",
    "role": 4,
    "pwHash": "6fab48348cbe1a34e7da9bab4f5003fd",
    "lastLogin": 0
  }


### Insert new user
PUT http://localhost:8083/api/team/insert/user HTTP/1.1
Authorization: Basic {{adminKey}}
Content-Type: application/json

{
  "botId": "5ca24489-6b10-4db0-a62d-b85159fab44c",
  "firstName": "James",
  "id": "fb94a63fcbda7e5b80573d82ea9a554b",
  "lastLogin": 0,
  "lastName": "Dean",
  "pwHash": "12a6896d0ef35c47d693788319ff5693",
  "role": 4,
  "teamId": "d72889fc-2db0-4d82-a39f-b1422b2f75f4",
  "userName": "Kreebog"
}

###
DELETE http://localhost:8083/api/team/delete/user/f75740cf577ffff8f943b54bf0a7c850 HTTP/1.1
Authorization: Basic {{adminKey}}
