@userName = Test-User-1

GET http://localhost:8083/api/team/get/user HTTP/1.1

###
GET http://localhost:8083/api/team/get/user?userName={{userName}} HTTP/1.1

###

PUT http://localhost:8083/api/team/insert/user HTTP/1.1
Content-Type: application/json

{
  "botId": "Bot-1",
  "firstName": "Test",
  "id": "f75740cf577ffff8f943b54bf0a7c850",
  "lastLogin": 0,
  "lastName": "User",
  "pwHash": "a4b9e35e64240d3c079c997741f0ba95",
  "role": 0,
  "teamId": "Team-1",
  "userName": "Test-User-1"
}

###

PUT http://localhost:8083/api/team/update/user HTTP/1.1
Content-Type: application/json

{
  "botId": "Bot-1",
  "firstName": "Test",
  "id": "f75740cf577ffff8f943b54bf0a7c850",
  "lastLogin": 0,
  "lastName": "User",
  "pwHash": "forced-pw-hash-update",
  "role": 0,
  "teamId": "Team-1",
  "userName": "Test-User-1"
}

###

DELETE http://localhost:8083/api/team/delete/user/f75740cf577ffff8f943b54bf0a7c850 HTTP/1.1