@adminKey = a3JlZWJvZzoxc3VwZXIx 
@assistantKey = RFJvZ2VyczpEUm9nZXJz
@invalidKey = dGVzdDpndXk=
@ocpKey = b3BlbnNoaWZ0Ok9wZW5TaGlmdF9QYXNzd29yZA==

### Request Probes
GET http://mazemasterjs.com/api/team/probes/live HTTP/1.1
Authorization: Basic {{ocpKey}}
Content-Type: application/json

### Rquest list of users
GET http://mazemasterjs.com/api/team/get/user HTTP/1.1
Authorization: Basic {{ocpKey}}

### Request count of teams
GET http://localhost:8083/api/team/count HTTP/1.1
Authorization: Basic {{assistantKey}}

### Request list of teams
GET http://mazemasterjs.com/api/team/get
Content-Type: application/json
Authorization: Basic {{adminKey}}

### Request a team
GET http://mazemasterjs.com/api/team/get?id=d72889fc-2db0-4d82-a39f-b1422b2f75f4
Content-Type: application/json
Authorization: Basic {{ocpKey}}

### Request specific user
GET http://localhost:8083/api/team/get/user?userName=OpenShift HTTP/1.1
Authorization: Basic {{adminKey}}

### Update User
PUT http://localhost:8083/api/team/update/user HTTP/1.1
Authorization: Basic {{adminKey}}
Content-Type: application/json

 {
    "id": "OpenShift",
    "userName": "openshift",
    "firstName": "Open",
    "lastName": "Shift",
    "teamId": "N/A",
    "botId": "N/A",
    "role": 4,
    "pwHash": "6fab48348cbe1a34e7da9bab4f5003fd",
    "lastLogin": 0
  }


### Insert new user
PUT http://localhost:8083/api/team/insert/user HTTP/1.1
Authorization: Basic {{adminKey}}
Content-Type: application/json

{
  "botId": "5ca24489-6b10-4db0-a62d-b85159fab44c",
  "firstName": "James",
  "id": "fb94a63fcbda7e5b80573d82ea9a554b",
  "lastLogin": 0,
  "lastName": "Dean",
  "pwHash": "12a6896d0ef35c47d693788319ff5693",
  "role": 4,
  "teamId": "d72889fc-2db0-4d82-a39f-b1422b2f75f4",
  "userName": "Kreebog"
}

###
DELETE http://localhost:8083/api/team/delete/user/f75740cf577ffff8f943b54bf0a7c850 HTTP/1.1
Authorization: Basic {{adminKey}}

### Get mazes
GET http://mazemasterjs.com/api/maze/get?id=5:5:10:DEBUG_v1.0.0 HTTP/1.1
Authorization: Basic {{ocpKey}}


### update maze
PUT http://localhost:8081/api/maze/update HTTP/1.1
Authorization: Basic {{ocpKey}}
Content-Type: application/json

{
    "id": "5:5:10:DEBUG_v1.0.0",
    "height": 5,
    "width": 5,
    "challenge": 10,
    "name": "zzz_DEBUG",
    "seed": "none",
    "cells": [
      [
        {
          "pos": {
            "row": 0,
            "col": 0
          },
          "exits": 6,
          "tags": 12,
          "traps": 0,
          "visits": 0,
          "lastVisit": 0,
          "notes": []
        },
        {
          "pos": {
            "row": 0,
            "col": 1
          },
          "exits": 10,
          "tags": 12,
          "traps": 0,
          "visits": 0,
          "lastVisit": 0,
          "notes": []
        },
        {
          "pos": {
            "row": 0,
            "col": 2
          },
          "exits": 6,
          "tags": 12,
          "traps": 0,
          "visits": 0,
          "lastVisit": 0,
          "notes": []
        },
        {
          "pos": {
            "row": 0,
            "col": 3
          },
          "exits": 10,
          "tags": 12,
          "traps": 0,
          "visits": 0,
          "lastVisit": 0,
          "notes": []
        },
        {
          "pos": {
            "row": 0,
            "col": 4
          },
          "exits": 3,
          "tags": 13,
          "traps": 0,
          "visits": 0,
          "lastVisit": 0,
          "notes": []
        }
      ],
      [
        {
          "pos": {
            "row": 1,
            "col": 0
          },
          "exits": 3,
          "tags": 12,
          "traps": 256,
          "visits": 0,
          "lastVisit": 0,
          "notes": []
        },
        {
          "pos": {
            "row": 1,
            "col": 1
          },
          "exits": 3,
          "tags": 128,
          "traps": 1,
          "visits": 0,
          "lastVisit": 0,
          "notes": []
        },
        {
          "pos": {
            "row": 1,
            "col": 2
          },
          "exits": 3,
          "tags": 16,
          "traps": 1,
          "visits": 0,
          "lastVisit": 0,
          "notes": []
        },
        {
          "pos": {
            "row": 1,
            "col": 3
          },
          "exits": 3,
          "tags": 12,
          "traps": 4,
          "visits": 0,
          "lastVisit": 0,
          "notes": []
        },
        {
          "pos": {
            "row": 1,
            "col": 4
          },
          "exits": 3,
          "tags": 12,
          "traps": 1,
          "visits": 0,
          "lastVisit": 0,
          "notes": []
        }
      ],
      [
        {
          "pos": {
            "row": 2,
            "col": 0
          },
          "exits": 3,
          "tags": 12,
          "traps": 0,
          "visits": 0,
          "lastVisit": 0,
          "notes": []
        },
        {
          "pos": {
            "row": 2,
            "col": 1
          },
          "exits": 3,
          "tags": 12,
          "traps": 0,
          "visits": 0,
          "lastVisit": 0,
          "notes": []
        },
        {
          "pos": {
            "row": 2,
            "col": 2
          },
          "exits": 3,
          "tags": 12,
          "traps": 0,
          "visits": 0,
          "lastVisit": 0,
          "notes": []
        },
        {
          "pos": {
            "row": 2,
            "col": 3
          },
          "exits": 3,
          "tags": 12,
          "traps": 0,
          "visits": 0,
          "lastVisit": 0,
          "notes": []
        },
        {
          "pos": {
            "row": 2,
            "col": 4
          },
          "exits": 3,
          "tags": 12,
          "traps": 0,
          "visits": 0,
          "lastVisit": 0,
          "notes": []
        }
      ],
      [
        {
          "pos": {
            "row": 3,
            "col": 0
          },
          "exits": 3,
          "tags": 12,
          "traps": 0,
          "visits": 0,
          "lastVisit": 0,
          "notes": []
        },
        {
          "pos": {
            "row": 3,
            "col": 1
          },
          "exits": 3,
          "tags": 12,
          "traps": 0,
          "visits": 0,
          "lastVisit": 0,
          "notes": []
        },
        {
          "pos": {
            "row": 3,
            "col": 2
          },
          "exits": 3,
          "tags": 12,
          "traps": 64,
          "visits": 0,
          "lastVisit": 0,
          "notes": []
        },
        {
          "pos": {
            "row": 3,
            "col": 3
          },
          "exits": 3,
          "tags": 12,
          "traps": 4,
          "visits": 0,
          "lastVisit": 0,
          "notes": []
        },
        {
          "pos": {
            "row": 3,
            "col": 4
          },
          "exits": 3,
          "tags": 12,
          "traps": 2,
          "visits": 0,
          "lastVisit": 0,
          "notes": []
        }
      ],
      [
        {
          "pos": {
            "row": 4,
            "col": 0
          },
          "exits": 3,
          "tags": 14,
          "traps": 0,
          "visits": 0,
          "lastVisit": 0,
          "notes": []
        },
        {
          "pos": {
            "row": 4,
            "col": 1
          },
          "exits": 5,
          "tags": 12,
          "traps": 0,
          "visits": 0,
          "lastVisit": 0,
          "notes": []
        },
        {
          "pos": {
            "row": 4,
            "col": 2
          },
          "exits": 9,
          "tags": 12,
          "traps": 0,
          "visits": 0,
          "lastVisit": 0,
          "notes": []
        },
        {
          "pos": {
            "row": 4,
            "col": 3
          },
          "exits": 5,
          "tags": 12,
          "traps": 0,
          "visits": 0,
          "lastVisit": 0,
          "notes": []
        },
        {
          "pos": {
            "row": 4,
            "col": 4
          },
          "exits": 9,
          "tags": 12,
          "traps": 0,
          "visits": 0,
          "lastVisit": 0,
          "notes": []
        }
      ]
    ],
    "textRender": "+ S +---+---+---+---+\n| . | . | . | . | . |\n+---+---+---+---+   +\n| . | . | . | . | . |\n+   +   +   +   +   +\n| . | . | . | . | . |\n+   +   +   +   +   +\n| . | . | . | . | . |\n+   +   +   +   +   +\n| . | . | . | . | . |\n+ F +---+---+---+---+\n",
    "startCell": {
      "row": 0,
      "col": 4
    },
    "finishCell": {
      "row": 4,
      "col": 0
    },
    "shortestPathLength": 25,
    "trapCount": 10,
    "note": "",
    "lastUpdated": 1561305458097
  }